// <auto-generated />
using System;
using FirebirdSql.EntityFrameworkCore.Firebird.Metadata;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YusurIntegration.Data;

#nullable disable

namespace YusurIntegration.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 31);

            modelBuilder.Entity("YusurIntegration.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActivityId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)");

                    b.Property<string>("ArabicInstructions")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("GenericCode")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Instructions")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool?>("Isapproved")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("Itemno")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)");

                    b.Property<int?>("Refills")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SelectedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedTradeCode")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("authStatus")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("rejectionReason")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("YusurIntegration.Models.ApiToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccessToken")
                        .HasMaxLength(2000)
                        .HasColumnType("VARCHAR(2000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<bool>("IsValid")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime?>("LastUsed")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Licence")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.ToTable("ApiTokens");
                });

            modelBuilder.Entity("YusurIntegration.Models.ApprovedDrug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("GenericCode")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("ItemNo")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("PriorityOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sfdacode")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("ApprovedDrugs");
                });

            modelBuilder.Entity("YusurIntegration.Models.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("VARCHAR(256)");

                    b.Property<string>("BranchLicense")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<DateOnly?>("DeliveryDate")
                        .HasColumnType("DATE");

                    b.Property<string>("DeliveryTimeSlotEndTime")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("DeliveryTimeSlotId")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("DeliveryTimeSlotStartTime")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("ErxReference")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("IsPickup")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("Status")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("VendorId")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("failureReason")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("OrderId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("YusurIntegration.Models.OrderStatusHistory", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("VARCHAR(256)");

                    b.Property<string>("FailureReason")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TIMESTAMP");

                    b.HasKey("OrderId");

                    b.ToTable("OrderStatusHistory");
                });

            modelBuilder.Entity("YusurIntegration.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)");

                    b.Property<string>("bloodGroup")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("dateOfBirth")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("gender")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("lastName")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("memberId")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("nationalId")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("YusurIntegration.Models.PendingMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BranchLicense")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("isdelivered")
                        .HasColumnType("BOOLEAN");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("PendingMessages");
                });

            modelBuilder.Entity("YusurIntegration.Models.Pharmacies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PharmacyName")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("YusurPassword")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("YusurUser")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("isGroup")
                        .HasColumnType("BOOLEAN");

                    b.HasKey("Id");

                    b.ToTable("Pharmacies");
                });

            modelBuilder.Entity("YusurIntegration.Models.PharmacyGroups", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("Id");

                    b.ToTable("PharmacyGroups");
                });

            modelBuilder.Entity("YusurIntegration.Models.ShippingAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)");

                    b.Property<string>("addressLine1")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("addressLine2")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("area")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("city")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("ShippingAddress");
                });

            modelBuilder.Entity("YusurIntegration.Models.StockTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BranchLicense")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)");

                    b.Property<string>("GenericCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)");

                    b.Property<string>("ItemNo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TIMESTAMP");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("storecode")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemNo", "BranchLicense", "GenericCode")
                        .IsUnique();

                    b.ToTable("StockTable");
                });

            modelBuilder.Entity("YusurIntegration.Models.TradeDrug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActivityForeignId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivityId")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActivityForeignId");

                    b.ToTable("TradeDrugs");
                });

            modelBuilder.Entity("YusurIntegration.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("YusurIntegration.Models.WasfatyDrugs", b =>
                {
                    b.Property<int>("DrugId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("drugId")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AtcCode")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("atcCode");

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("barcode");

                    b.Property<string>("Category1")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("category1");

                    b.Property<string>("Category2")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("category2");

                    b.Property<string>("Company")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("company");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("createdDate");

                    b.Property<string>("DiscontinueDate")
                        .HasMaxLength(12)
                        .HasColumnType("VARCHAR(12)")
                        .HasColumnName("discontinueDate");

                    b.Property<double?>("DivisibleFactor")
                        .HasColumnType("DOUBLE PRECISION")
                        .HasColumnName("divisibleFactor");

                    b.Property<string>("Division")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("division");

                    b.Property<string>("DosageForm")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("dosageForm");

                    b.Property<string>("DosageFormCode")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("dosageFormCode");

                    b.Property<string>("DosageOrderForm")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("dosageOrderForm");

                    b.Property<string>("DosageUnit")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("dosageUnit");

                    b.Property<int?>("DosageUnitId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dosageUnitId");

                    b.Property<double?>("DoseStrength")
                        .HasColumnType("DOUBLE PRECISION")
                        .HasColumnName("doseStrength");

                    b.Property<string>("DoseStrengthUnit")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("doseStrengthUnit");

                    b.Property<int?>("DoseStrengthUnitId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("doseStrengthUnitId");

                    b.Property<string>("DrugCode")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("drugCode");

                    b.Property<string>("GenericCode")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("genericCode");

                    b.Property<string>("GenericName")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("genericName");

                    b.Property<int?>("GranularUnit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("granularUnit");

                    b.Property<string>("Id")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("id");

                    b.Property<string>("Ingredients")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("ingredients");

                    b.Property<bool?>("IsAlternative")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("isAlternative");

                    b.Property<string>("IsControlled")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("isControlled");

                    b.Property<bool?>("IsDelivery")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("isDelivery");

                    b.Property<bool?>("IsDivisible")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("isDivisible");

                    b.Property<bool?>("IsDivisibleFactor")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("isDivisibleFactor");

                    b.Property<bool?>("IsHazardous")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("isHazardous");

                    b.Property<bool?>("IsHighAlert")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("isHighAlert");

                    b.Property<bool?>("IsInfiniteDivisible")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("isInfiniteDivisible");

                    b.Property<bool?>("IsLasa")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("isLasa");

                    b.Property<int?>("ItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("itemId");

                    b.Property<string>("ListId")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("listId");

                    b.Property<string>("MappingScientificCode")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("mappingScientificCode");

                    b.Property<int?>("MaxRefill")
                        .HasColumnType("INTEGER")
                        .HasColumnName("maxRefill");

                    b.Property<string>("PackageSize")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("packageSize");

                    b.Property<string>("PackageType")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("packageType");

                    b.Property<double?>("PackageVolume")
                        .HasColumnType("DOUBLE PRECISION")
                        .HasColumnName("packageVolume");

                    b.Property<double?>("Price")
                        .HasColumnType("DOUBLE PRECISION")
                        .HasColumnName("price");

                    b.Property<DateTime?>("PublishDate")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("publishDate");

                    b.Property<string>("RegOwner")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("regOwner");

                    b.Property<string>("Region")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("region");

                    b.Property<string>("RoaCode")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("roaCode");

                    b.Property<string>("RouteOfAdmin")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("routeOfAdmin");

                    b.Property<string>("Source")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .HasMaxLength(12)
                        .HasColumnType("VARCHAR(12)")
                        .HasColumnName("status");

                    b.Property<string>("Strength")
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("strength");

                    b.Property<string>("SuggestedRouteOfAdmin")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("suggestedRouteOfAdmin");

                    b.Property<string>("TradeName")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("tradeName");

                    b.Property<string>("UnitType")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("unitType");

                    b.Property<int?>("UnitTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unitTypeId");

                    b.Property<string>("UpdatedDate")
                        .HasMaxLength(12)
                        .HasColumnType("VARCHAR(12)")
                        .HasColumnName("updatedDate");

                    b.Property<string>("VerbDescription")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("verbDescription");

                    b.Property<string>("VerbSecondLanguageDescription")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("verbSecondLanguageDescription");

                    b.Property<int?>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.Property<double?>("Volume")
                        .HasColumnType("DOUBLE PRECISION")
                        .HasColumnName("volume");

                    b.Property<string>("VolumeUnit")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("volumeUnit");

                    b.Property<int?>("VolumeUnitId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("volumeUnitId");

                    b.HasKey("DrugId");

                    b.ToTable("WasfatyDrugs");
                });

            modelBuilder.Entity("YusurIntegration.Models.WebhookLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BranchConnected")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("BranchLicense")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("OrderId")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Payload")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Status")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("WebhookType")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("Id");

                    b.ToTable("WebhookLogs");
                });

            modelBuilder.Entity("YusurIntegration.Models.YusurUsers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Licence")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("storecode")
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR(10)");

                    b.Property<string>("storename")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.ToTable("YusurUsers");
                });

            modelBuilder.Entity("YusurIntegration.Models.Activity", b =>
                {
                    b.HasOne("YusurIntegration.Models.Order", "Order")
                        .WithMany("Activities")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("YusurIntegration.Models.Patient", b =>
                {
                    b.HasOne("YusurIntegration.Models.Order", "Order")
                        .WithOne("Patient")
                        .HasForeignKey("YusurIntegration.Models.Patient", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("YusurIntegration.Models.ShippingAddress", b =>
                {
                    b.HasOne("YusurIntegration.Models.Order", "Order")
                        .WithOne("ShippingAddress")
                        .HasForeignKey("YusurIntegration.Models.ShippingAddress", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("YusurIntegration.Models.Coordinates", "Coordinates", b1 =>
                        {
                            b1.Property<int>("ShippingAddressId")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("latitude")
                                .HasColumnType("DOUBLE PRECISION");

                            b1.Property<double>("longitude")
                                .HasColumnType("DOUBLE PRECISION");

                            b1.HasKey("ShippingAddressId");

                            b1.ToTable("ShippingAddress");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAddressId");
                        });

                    b.Navigation("Coordinates");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("YusurIntegration.Models.TradeDrug", b =>
                {
                    b.HasOne("YusurIntegration.Models.Activity", "Activity")
                        .WithMany("TradeDrugs")
                        .HasForeignKey("ActivityForeignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("YusurIntegration.Models.Activity", b =>
                {
                    b.Navigation("TradeDrugs");
                });

            modelBuilder.Entity("YusurIntegration.Models.Order", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Patient");

                    b.Navigation("ShippingAddress");
                });
#pragma warning restore 612, 618
        }
    }
}
